from typing import Any, Union, Callable, Tuple, List

from src.items.items import Item
import dearpygui.dearpygui as dpg

from src.items.sliders.slider import Slider


class SliderFloat(Slider):
    def __init__(self,
                 *,
                 label: str = None,
                 user_data: Any = None,
                 use_internal_label: bool = True,
                 tag: Union[int, str] = 0,
                 width: int = 0,
                 height: int = 0,
                 indent: int = -1,
                 parent: Union[int, str] = 0,
                 before: Union[int, str] = 0,
                 source: Union[int, str] = 0,
                 payload_type: str = '$$DPG_PAYLOAD',
                 callback: Callable = None,
                 drag_callback: Callable = None,
                 drop_callback: Callable = None,
                 show: bool = True,
                 enabled: bool = True,
                 pos: Union[List[int], Tuple[int, ...]] = [],
                 filter_key: str = '',
                 tracked: bool = False,
                 track_offset: float = 0.5,
                 default_value: float = 0.0,
                 vertical: bool = False,
                 no_input: bool = False,
                 clamped: bool = False,
                 min_value: float = 0.0,
                 max_value: float = 100.0,
                 format: str = '%.3f',
                 **kwargs
                 ):
        self.identifier = dpg.add_slider_float(label=label,
                                               user_data=user_data,
                                               use_internal_label=use_internal_label,
                                               tag=tag,
                                               width=width,
                                               height=height,
                                               indent=indent,
                                               parent=parent,
                                               before=before,
                                               source=source,
                                               payload_type=payload_type,
                                               callback=callback,
                                               drag_callback=drag_callback,
                                               drop_callback=drop_callback,
                                               show=show,
                                               enabled=enabled,
                                               pos=pos,
                                               filter_key=filter_key,
                                               tracked=tracked,
                                               track_offset=track_offset,
                                               default_value=default_value,
                                               vertical=vertical,
                                               no_input=no_input,
                                               clamped=clamped,
                                               min_value=min_value,
                                               max_value=max_value,
                                               format=format,
                                               **kwargs)
